[package]
name = "email-newsletter"
version = "0.1.0"
authors = ["Yousef Farge <yousef.farge@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "email-newsletter"

[dependencies]
actix-web = "4.9.0"
reqwest = "0.12.9"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
